name: Trigger auto deployment for micronaut-example

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/micronaut-example-AutoDeployTrigger-76e35a3a-a26d-4ae1-b16f-7dbb4bd2081b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: basicrepository.azurecr.io
          username: ${{ secrets.MICRONAUTEXAMPLE_REGISTRY_USERNAME }}
          password: ${{ secrets.MICRONAUTEXAMPLE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: basicrepository.azurecr.io/micronaut-example:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MICRONAUTEXAMPLE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n micronaut-example -g explore-container --server basicrepository.azurecr.io --username  ${{ secrets.MICRONAUTEXAMPLE_REGISTRY_USERNAME }} --password ${{ secrets.MICRONAUTEXAMPLE_REGISTRY_PASSWORD }}
            az containerapp update -n micronaut-example -g explore-container --image basicrepository.azurecr.io/micronaut-example:${{ github.sha }}
